# -*- coding: utf-8 -*-
"""FireDemoWithCached.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwpJ8IzVJJ6mXK8xhoMZqKGIzQeREXdt
"""

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 1 — Mount Drive & install dependencies
# ═══════════════════════════════════════════════════════════════════════════════
from google.colab import drive
drive.mount('/content/drive')

import subprocess
subprocess.run(['pip', 'install', 'rasterio', '-q'], capture_output=True)

import os, glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.colors import LinearSegmentedColormap
from scipy.ndimage import gaussian_filter
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F

print('All imports OK ✅')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 2 — Configuration
# ═══════════════════════════════════════════════════════════════════════════════
CACHE_DIR     = '/content/drive/MyDrive/ts-satfire/cache_frpinput_seq1_sp128_trimmed'
SATELLITE_DIR = '/content/drive/MyDrive/ts-satfire/satellite_export'
MODEL_PATH    = '/content/drive/MyDrive/ts-satfire/deepfire_frpinput_best.pt'
SAVE_DIR      = '/content/drive/MyDrive/ts-satfire'

SPATIAL_SIZE   = 128
PRED_THRESHOLD = 0.5
FIRE_PEAK      = 1.0
FIRE_SIGMA     = 5.0

# ── List available events from cache ─────────────────────────────────────────
all_cache_files = sorted(glob.glob(os.path.join(CACHE_DIR, '*.pt')))
if not all_cache_files:
    raise FileNotFoundError(f'No .pt files found in {CACHE_DIR}')

# Extract unique event names
event_names = sorted(set(
    os.path.basename(f).split('_seq')[0] for f in all_cache_files
))
print(f'Cache         : {CACHE_DIR}')
print(f'Total files   : {len(all_cache_files)}')
print(f'Unique events : {len(event_names)}')
print('\nFirst 10 events:')
for i, e in enumerate(event_names[:10]):
    seqs = [f for f in all_cache_files if os.path.basename(f).startswith(e)]
    print(f'  [{i:>3}]  {e}  ({len(seqs)} sequences)')


# ═══════════════════════════════════════════════════════════════════════════════
# CELL 2b — Model Architecture
# ═══════════════════════════════════════════════════════════════════════════════
class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride=stride,
                      padding=padding, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True))
    def forward(self, x): return self.block(x)

class ResidualCNNBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Sequential(ConvBNReLU(in_ch, out_ch),
                                  ConvBNReLU(out_ch, out_ch))
        self.skip = (nn.Conv2d(in_ch, out_ch, 1, bias=False)
                     if in_ch != out_ch else nn.Identity())
    def forward(self, x):
        return F.relu(self.conv(x) + self.skip(x), inplace=True)

class SpatialEncoder(nn.Module):
    def __init__(self, viirs_channels, lulc_embed_dim, embed_dim):
        super().__init__()
        in_ch = viirs_channels + lulc_embed_dim
        self.enc1  = ResidualCNNBlock(in_ch, 32)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.enc2  = ResidualCNNBlock(32, 64)
        self.pool2 = nn.MaxPool2d(2, 2)
        self.enc3  = ResidualCNNBlock(64, embed_dim)
        self.pool3 = nn.MaxPool2d(2, 2)
    def forward(self, x):
        s1 = self.enc1(x)
        s2 = self.enc2(self.pool1(s1))
        s3 = self.enc3(self.pool2(s2))
        return s1, s2, s3, self.pool3(s3)

class SpatiotemporalTransformer(nn.Module):
    def __init__(self, embed_dim, num_heads, num_layers, seq_len,
                 spatial_size, dropout):
        super().__init__()
        Hf = spatial_size // 8
        n  = Hf * Hf
        self.spatial_pos  = nn.Parameter(
            torch.randn(1, 1, n, embed_dim) * 0.02)
        self.temporal_pos = nn.Parameter(
            torch.randn(1, seq_len, 1, embed_dim) * 0.02)
        layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, nhead=num_heads,
            dim_feedforward=embed_dim*4, dropout=dropout,
            activation='gelu', batch_first=True, norm_first=True)
        self.transformer = nn.TransformerEncoder(layer, num_layers)
        self.norm        = nn.LayerNorm(embed_dim)
    def forward(self, x):
        B,T,D,H,W = x.shape
        x = x.view(B,T,D,H*W).permute(0,1,3,2)
        x = x + self.spatial_pos + self.temporal_pos
        x = self.norm(self.transformer(x.reshape(B,T*H*W,D)))
        return x.view(B,T,H*W,D).permute(0,1,3,2).contiguous().view(B,T,D,H,W)

class TemporalAttentionPooling(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.score_net = nn.Sequential(
            nn.Conv2d(embed_dim, embed_dim//2, 1),
            nn.ReLU(inplace=True),
            nn.Conv2d(embed_dim//2, 1, 1))
    def forward(self, x):
        B,T,D,H,W = x.shape
        w = F.softmax(
            self.score_net(x.view(B*T,D,H,W)).view(B,T,H*W).mean(2), dim=1)
        return (x * w.view(B,T,1,1,1)).sum(1), w

class UNetDecoder(nn.Module):
    def __init__(self, embed_dim=128):
        super().__init__()
        self.up3     = nn.Sequential(
            nn.ConvTranspose2d(embed_dim,64,4,stride=2,padding=1),
            nn.BatchNorm2d(64), nn.ReLU(inplace=True))
        self.refine3 = ResidualCNNBlock(64+embed_dim, 64)
        self.up2     = nn.Sequential(
            nn.ConvTranspose2d(64,32,4,stride=2,padding=1),
            nn.BatchNorm2d(32), nn.ReLU(inplace=True))
        self.refine2 = ResidualCNNBlock(32+64, 32)
        self.up1     = nn.Sequential(
            nn.ConvTranspose2d(32,16,4,stride=2,padding=1),
            nn.BatchNorm2d(16), nn.ReLU(inplace=True))
        self.refine1 = ResidualCNNBlock(16+32, 16)
        self.head    = nn.Conv2d(16, 1, 1)
    def forward(self, bt, s3, s2, s1):
        x = self.refine3(torch.cat([self.up3(bt), s3], 1))
        x = self.refine2(torch.cat([self.up2(x),  s2], 1))
        x = self.refine1(torch.cat([self.up1(x),  s1], 1))
        return torch.sigmoid(self.head(x))

class DeepFireForecaster(nn.Module):
    def __init__(self, viirs_channels=4, lulc_classes=12, lulc_embed_dim=8,
                 embed_dim=128, num_heads=4, num_layers=3, seq_len=1,
                 spatial_size=128, dropout=0.1):
        super().__init__()
        self.seq_len       = seq_len
        self.lulc_embed    = nn.Embedding(lulc_classes, lulc_embed_dim)
        self.spatial_encoder = SpatialEncoder(viirs_channels,
                                              lulc_embed_dim, embed_dim)
        self.transformer   = SpatiotemporalTransformer(
            embed_dim, num_heads, num_layers, seq_len, spatial_size, dropout)
        self.temporal_pool = TemporalAttentionPooling(embed_dim)
        self.decoder       = UNetDecoder(embed_dim)
    def forward(self, viirs, lulc):
        B,T,C,H,W = viirs.shape
        lulc_emb = self.lulc_embed(lulc).permute(0,3,1,2)
        lulc_rep = lulc_emb.unsqueeze(1).expand(-1,T,-1,-1,-1)
        x_in = torch.cat([viirs.view(B*T,C,H,W),
                          lulc_rep.reshape(B*T,8,H,W)], dim=1)
        s1,s2,s3,bt = self.spatial_encoder(x_in)
        _,D,Hb,Wb   = bt.shape
        bt_seq = self.transformer(bt.view(B,T,D,Hb,Wb))
        pooled, attn = self.temporal_pool(bt_seq)
        s3_agg = s3.view(B,T,s3.shape[1],*s3.shape[2:]).mean(1)
        s2_agg = s2.view(B,T,s2.shape[1],*s2.shape[2:]).mean(1)
        s1_agg = s1.view(B,T,s1.shape[1],*s1.shape[2:]).mean(1)
        return self.decoder(pooled, s3_agg, s2_agg, s1_agg), attn

print('✅ Architecture classes defined.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 3 — Load model and pick event
# ═══════════════════════════════════════════════════════════════════════════════
DEVICE     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
checkpoint = torch.load(MODEL_PATH, map_location=DEVICE)
enc_weight = checkpoint['model']['spatial_encoder.enc1.conv.0.block.0.weight']
C_VIIRS    = enc_weight.shape[1] - 8

model = DeepFireForecaster(viirs_channels=C_VIIRS).to(DEVICE)
model.load_state_dict(checkpoint['model'])
model.eval()
print(f'Model loaded ✅  epoch={checkpoint["epoch"]}  '
      f'val_iou={checkpoint["val_iou"]:.4f}')

# ── Pick event and sequence ───────────────────────────────────────────────────
EVENT_NAME = event_names[0]   # ← change to any event name from the list above
SEQ        = 0                # ← 0 = seq000, 1 = seq001

cache_file = os.path.join(CACHE_DIR, f'{EVENT_NAME}_seq{SEQ:03d}.pt')
if not os.path.exists(cache_file):
    raise FileNotFoundError(f'Cache file not found: {cache_file}')

sample   = torch.load(cache_file, weights_only=True)
viirs_np = sample['viirs'].squeeze(0).numpy()   # [4, S, S]
lulc_t   = sample['lulc']                       # [S, S]

print(f'\nEvent    : {EVENT_NAME}')
print(f'Sequence : seq{SEQ:03d}')
print(f'viirs    : {tuple(sample["viirs"].shape)}')
print(f'lulc     : {tuple(sample["lulc"].shape)}')

# ── Load satellite image ──────────────────────────────────────────────────────
sat_path = os.path.join(SATELLITE_DIR, f'{EVENT_NAME}.png')
if os.path.exists(sat_path):
    sat_np = np.array(Image.open(sat_path).convert('RGB').resize(
        (SPATIAL_SIZE, SPATIAL_SIZE), Image.LANCZOS))
    print(f'Satellite image loaded ✅')
else:
    sat_np = np.zeros((SPATIAL_SIZE, SPATIAL_SIZE, 3), dtype=np.uint8)
    print(f'⚠️  No satellite image found at {sat_path} — using blank background')

print(f'\nReady ✅ — run Cell 4 to pick your ignition area')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 4 — Pick ignition area
# ═══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle(
    f'{EVENT_NAME}  —  seq{SEQ:03d}\n'
    f'Image is {SPATIAL_SIZE}×{SPATIAL_SIZE} px  '
    f'(x = left→right,  y = top→bottom)',
    fontsize=11, fontweight='bold'
)

axes[0].imshow(sat_np)
axes[0].set_title('Satellite image', fontsize=10); axes[0].axis('off')

axes[1].imshow(sat_np)
step = SPATIAL_SIZE // 8
for i in range(0, SPATIAL_SIZE, step):
    axes[1].axhline(i, color='white', linewidth=0.4, alpha=0.6)
    axes[1].axvline(i, color='white', linewidth=0.4, alpha=0.6)
    if i > 0:
        axes[1].text(i, 2,  str(i), color='white', fontsize=6, ha='center')
        axes[1].text(2, i,  str(i), color='white', fontsize=6, va='center')
axes[1].set_title('Grid overlay', fontsize=10)
axes[1].set_xlim(0, SPATIAL_SIZE); axes[1].set_ylim(SPATIAL_SIZE, 0)
axes[1].axis('off')
plt.tight_layout(); plt.show()

# ── Set ignition box ──────────────────────────────────────────────────────────
IGN_X1 = 50; IGN_Y1 = 50   # ← top-left corner
IGN_X2 = 70; IGN_Y2 = 70   # ← bottom-right corner

S = SPATIAL_SIZE - 1
x1 = max(0, min(IGN_X1, S)); y1 = max(0, min(IGN_Y1, S))
x2 = max(0, min(IGN_X2, S)); y2 = max(0, min(IGN_Y2, S))

# Build FRP input from drawn box
frp_drawn = np.zeros((SPATIAL_SIZE, SPATIAL_SIZE), dtype=np.float32)
frp_drawn[y1:y2+1, x1:x2+1] = FIRE_PEAK
frp_drawn = gaussian_filter(frp_drawn, sigma=FIRE_SIGMA)
if frp_drawn.max() > 0:
    frp_drawn = frp_drawn / frp_drawn.max() * FIRE_PEAK

# Preview
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].imshow(sat_np)
axes[0].add_patch(patches.Rectangle(
    (x1,y1), x2-x1, y2-y1,
    linewidth=2, edgecolor='red', facecolor='red', alpha=0.35))
axes[0].set_title(f'Ignition box  x=[{x1},{x2}]  y=[{y1},{y2}]', fontsize=10)
axes[0].axis('off')

axes[1].imshow(sat_np)
axes[1].imshow(frp_drawn, cmap='hot', vmin=0, vmax=1, alpha=0.7)
axes[1].set_title('FRP input channel', fontsize=10); axes[1].axis('off')

plt.tight_layout(); plt.show()
print('Happy with the box? Run Cell 5 to predict.')
print('If not, adjust IGN_X1/Y1/X2/Y2 and re-run this cell.')

# ═══════════════════════════════════════════════════════════════════════════════
# CELL 5 — Inject fire and predict
# ═══════════════════════════════════════════════════════════════════════════════
fire_cmap = LinearSegmentedColormap.from_list(
    'fire', [(0,0,0,0),(1,0.5,0,0.5),(1,0,0,0.85)], N=256)

# ── Replace FRP channel with drawn fire ───────────────────────────────────────
viirs_injected = viirs_np.copy()
viirs_injected[3] = frp_drawn   # channel 3 = FRP

# ── Run model ─────────────────────────────────────────────────────────────────
viirs_t = torch.tensor(viirs_injected).unsqueeze(0).unsqueeze(0).to(DEVICE)
lulc_in = lulc_t.unsqueeze(0).to(DEVICE)

with torch.no_grad():
    pred_t, _ = model(viirs_t, lulc_in)

pred_np = pred_t.cpu().squeeze().numpy()

# ── Plot ──────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 4, figsize=(22, 5))
fig.suptitle(
    f'Fire Spread Prediction — {EVENT_NAME}  seq{SEQ:03d}\n'
    f'Threshold={PRED_THRESHOLD}',
    fontsize=11, fontweight='bold'
)

axes[0].imshow(sat_np)
axes[0].add_patch(patches.Rectangle(
    (x1,y1), x2-x1, y2-y1,
    linewidth=2, edgecolor='red', facecolor='red', alpha=0.35))
axes[0].set_title('Ignition Area', fontsize=10); axes[0].axis('off')

axes[1].imshow(sat_np)
axes[1].imshow(frp_drawn, cmap='hot', vmin=0, vmax=1, alpha=0.7)
axes[1].set_title('FRP Input\n(current fire state)', fontsize=10)
axes[1].axis('off')

axes[2].imshow(sat_np)
axes[2].imshow(pred_np, cmap=fire_cmap, vmin=0, vmax=1)
axes[2].set_title('Predicted Spread\n(next day)', fontsize=10)
axes[2].axis('off')

im = axes[3].imshow(pred_np, cmap='hot', vmin=0, vmax=1)
axes[3].set_title(f'Probability Map\n(max={pred_np.max():.3f})', fontsize=10)
axes[3].axis('off')
fig.colorbar(im, ax=axes[3], fraction=0.046, pad=0.04, label='Probability')

plt.tight_layout()
save_path = os.path.join(SAVE_DIR,
    f'demo_cached_{EVENT_NAME}_seq{SEQ:03d}.png')
os.makedirs(SAVE_DIR, exist_ok=True)
plt.savefig(save_path, dpi=200, bbox_inches='tight')
plt.show(); plt.close()
print(f'Saved → {save_path}')

fire_px = int((pred_np >= PRED_THRESHOLD).sum())
print(f'\nPrediction summary:')
print(f'  Input fire pixels  : {int((frp_drawn >= PRED_THRESHOLD).sum())}')
print(f'  Predicted fire px  : {fire_px} ({100*fire_px/SPATIAL_SIZE**2:.1f}%)')
print(f'  Max probability    : {pred_np.max():.4f}')