# -*- coding: utf-8 -*-
"""FireDemo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bmd4wZ3vGUiZIN0zKIRzm6OHGMmodvea
"""

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

import subprocess
subprocess.run(['pip', 'install', 'rasterio', '-q'], capture_output=True)

import os, glob, math, io, time
import numpy as np
import rasterio
import rasterio.warp
import requests
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.colors import LinearSegmentedColormap
from scipy.ndimage import gaussian_filter
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F

DATA_ROOT     = '/content/drive/MyDrive/ts-satfire/ts-satfire'
SAVE_DIR      = '/content/drive/MyDrive/ts-satfire'
MODEL_PATH    = '/content/drive/MyDrive/ts-satfire/deepfire_frpinput_best.pt'
SATELLITE_DIR = '/content/drive/MyDrive/ts-satfire/satellite_images'

EVENT_IDX     = 8     # which event to use
DAY_IDX       = 1    # which day within that event
ZOOM          = None  # None = auto

PRED_THRESHOLD = 0.5
OVERLAY_ALPHA  = 0.6

all_event_dirs = sorted([
    os.path.join(DATA_ROOT, d)
    for d in os.listdir(DATA_ROOT)
    if os.path.isdir(os.path.join(DATA_ROOT, d))
])
print(f'Total events : {len(all_event_dirs)}')
for i, d in enumerate(all_event_dirs[:10]):
    n_days = len(glob.glob(os.path.join(d, 'VIIRS_Day', '*.tif')))
    n_fire = len(glob.glob(os.path.join(d, 'FirePred',  '*.tif')))
    print(f'  [{i:>3}]  {os.path.basename(d)}  ({n_days} days  {n_fire} firepred)')


# Model Architecture

class ConvBNReLU(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, stride=1, padding=1):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel, stride=stride,
                      padding=padding, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True))
    def forward(self, x): return self.block(x)

class ResidualCNNBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Sequential(ConvBNReLU(in_ch, out_ch),
                                  ConvBNReLU(out_ch, out_ch))
        self.skip = (nn.Conv2d(in_ch, out_ch, 1, bias=False)
                     if in_ch != out_ch else nn.Identity())
    def forward(self, x):
        return F.relu(self.conv(x) + self.skip(x), inplace=True)

class SpatialEncoder(nn.Module):
    def __init__(self, viirs_channels, lulc_embed_dim, embed_dim):
        super().__init__()
        in_ch = viirs_channels + lulc_embed_dim
        self.enc1  = ResidualCNNBlock(in_ch, 32)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.enc2  = ResidualCNNBlock(32, 64)
        self.pool2 = nn.MaxPool2d(2, 2)
        self.enc3  = ResidualCNNBlock(64, embed_dim)
        self.pool3 = nn.MaxPool2d(2, 2)
    def forward(self, x):
        s1 = self.enc1(x)
        s2 = self.enc2(self.pool1(s1))
        s3 = self.enc3(self.pool2(s2))
        return s1, s2, s3, self.pool3(s3)

class SpatiotemporalTransformer(nn.Module):
    def __init__(self, embed_dim, num_heads, num_layers, seq_len,
                 spatial_size, dropout):
        super().__init__()
        Hf = spatial_size // 8
        n  = Hf * Hf
        self.spatial_pos  = nn.Parameter(
            torch.randn(1, 1, n, embed_dim) * 0.02)
        self.temporal_pos = nn.Parameter(
            torch.randn(1, seq_len, 1, embed_dim) * 0.02)
        layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, nhead=num_heads,
            dim_feedforward=embed_dim*4, dropout=dropout,
            activation='gelu', batch_first=True, norm_first=True)
        self.transformer = nn.TransformerEncoder(layer, num_layers)
        self.norm        = nn.LayerNorm(embed_dim)
    def forward(self, x):
        B,T,D,H,W = x.shape
        x = x.view(B,T,D,H*W).permute(0,1,3,2)
        x = x + self.spatial_pos + self.temporal_pos
        x = self.norm(self.transformer(x.reshape(B,T*H*W,D)))
        return x.view(B,T,H*W,D).permute(0,1,3,2).contiguous().view(B,T,D,H,W)

class TemporalAttentionPooling(nn.Module):
    def __init__(self, embed_dim):
        super().__init__()
        self.score_net = nn.Sequential(
            nn.Conv2d(embed_dim, embed_dim//2, 1),
            nn.ReLU(inplace=True),
            nn.Conv2d(embed_dim//2, 1, 1))
    def forward(self, x):
        B,T,D,H,W = x.shape
        w = F.softmax(
            self.score_net(x.view(B*T,D,H,W)).view(B,T,H*W).mean(2), dim=1)
        return (x * w.view(B,T,1,1,1)).sum(1), w

class UNetDecoder(nn.Module):
    def __init__(self, embed_dim=128):
        super().__init__()
        self.up3     = nn.Sequential(
            nn.ConvTranspose2d(embed_dim,64,4,stride=2,padding=1),
            nn.BatchNorm2d(64), nn.ReLU(inplace=True))
        self.refine3 = ResidualCNNBlock(64+embed_dim, 64)
        self.up2     = nn.Sequential(
            nn.ConvTranspose2d(64,32,4,stride=2,padding=1),
            nn.BatchNorm2d(32), nn.ReLU(inplace=True))
        self.refine2 = ResidualCNNBlock(32+64, 32)
        self.up1     = nn.Sequential(
            nn.ConvTranspose2d(32,16,4,stride=2,padding=1),
            nn.BatchNorm2d(16), nn.ReLU(inplace=True))
        self.refine1 = ResidualCNNBlock(16+32, 16)
        self.head    = nn.Conv2d(16, 1, 1)
    def forward(self, bt, s3, s2, s1):
        x = self.refine3(torch.cat([self.up3(bt), s3], 1))
        x = self.refine2(torch.cat([self.up2(x),  s2], 1))
        x = self.refine1(torch.cat([self.up1(x),  s1], 1))
        return torch.sigmoid(self.head(x))

class DeepFireForecaster(nn.Module):
    def __init__(self, viirs_channels=4, lulc_classes=12, lulc_embed_dim=8,
                 embed_dim=128, num_heads=4, num_layers=3, seq_len=1,
                 spatial_size=128, dropout=0.1):
        super().__init__()
        self.seq_len       = seq_len
        self.lulc_embed    = nn.Embedding(lulc_classes, lulc_embed_dim)
        self.spatial_encoder = SpatialEncoder(viirs_channels,
                                              lulc_embed_dim, embed_dim)
        self.transformer   = SpatiotemporalTransformer(
            embed_dim, num_heads, num_layers, seq_len, spatial_size, dropout)
        self.temporal_pool = TemporalAttentionPooling(embed_dim)
        self.decoder       = UNetDecoder(embed_dim)
    def forward(self, viirs, lulc):
        B,T,C,H,W = viirs.shape
        lulc_emb = self.lulc_embed(lulc).permute(0,3,1,2)
        lulc_rep = lulc_emb.unsqueeze(1).expand(-1,T,-1,-1,-1)
        x_in = torch.cat([viirs.view(B*T,C,H,W),
                          lulc_rep.reshape(B*T,8,H,W)], dim=1)
        s1,s2,s3,bt = self.spatial_encoder(x_in)
        _,D,Hb,Wb   = bt.shape
        bt_seq = self.transformer(bt.view(B,T,D,Hb,Wb))
        pooled, attn = self.temporal_pool(bt_seq)
        s3_agg = s3.view(B,T,s3.shape[1],*s3.shape[2:]).mean(1)
        s2_agg = s2.view(B,T,s2.shape[1],*s2.shape[2:]).mean(1)
        s1_agg = s1.view(B,T,s1.shape[1],*s1.shape[2:]).mean(1)
        return self.decoder(pooled, s3_agg, s2_agg, s1_agg), attn

print('✅ Architecture classes defined.')

# CELL 3 — Load model, VIIRS, LULC and satellite image

# Tile helpers
ESRI_URL = ("https://server.arcgisonline.com/ArcGIS/rest/services/"
            "World_Imagery/MapServer/tile/{z}/{y}/{x}")
HEADERS  = {'User-Agent': 'viirs-demo/1.0 (educational use)'}

def read_selected_bands(path, indices):
    with rasterio.open(path) as src:
        bands  = [np.nan_to_num(src.read(i+1).astype(np.float32), nan=0.0)
                  for i in indices]
        crs    = src.crs
        bounds = src.bounds
    return np.stack(bands, axis=0), crs, bounds

def read_band(path, band=1):
    with rasterio.open(path) as src:
        arr = src.read(band).astype(np.float32)
    return np.nan_to_num(arr, nan=0.0)

def normalise_arr(arr):
    out = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        b=arr[i]; bmin,bmax=b.min(),b.max()
        if bmax-bmin>1e-6: out[i]=(b-bmin)/(bmax-bmin)
    return out

def normalise_frp(arr):
    arr = np.clip(arr, 0.0, None)
    pos = arr[arr > 0]
    if len(pos) == 0: return arr
    p99 = max(float(np.percentile(pos, 99)), 1.0)
    return np.clip(arr / p99, 0.0, 1.0)

def resize_arr(a, size):
    t = torch.tensor(a, dtype=torch.float32).unsqueeze(0)
    t = F.interpolate(t, size=(size,size), mode='bilinear', align_corners=False)
    return t.squeeze(0).numpy()

def get_bbox_latlon(bounds, crs):
    xs   = [bounds.left, bounds.right, bounds.left,  bounds.right]
    ys   = [bounds.bottom, bounds.bottom, bounds.top, bounds.top]
    lons, lats = rasterio.warp.transform(crs, 'EPSG:4326', xs, ys)
    return min(lats), min(lons), max(lats), max(lons)

def lon_to_tile_x(lon, z): return int((lon+180)/360*2**z)
def lat_to_tile_y(lat, z):
    r = math.radians(lat)
    return int((1-math.log(math.tan(r)+1/math.cos(r))/math.pi)/2*2**z)
def tile_to_latlon(x, y, z):
    n = 2**z
    return math.degrees(math.atan(math.sinh(math.pi*(1-2*y/n)))), x/n*360-180
def auto_zoom(min_lat, min_lon, max_lat, max_lon, target_tiles=4):
    for z in range(18, 0, -1):
        if (lon_to_tile_x(max_lon,z)-lon_to_tile_x(min_lon,z)+1 <= target_tiles and
            lat_to_tile_y(min_lat,z)-lat_to_tile_y(max_lat,z)+1 <= target_tiles):
            return z
    return 6
def fetch_tile(x, y, z):
    resp = requests.get(ESRI_URL.format(x=x,y=y,z=z), headers=HEADERS, timeout=10)
    if resp.status_code != 200:
        return Image.new('RGB', (256,256), (180,180,180))
    return Image.open(io.BytesIO(resp.content)).convert('RGB')
def fetch_esri_image(min_lat, min_lon, max_lat, max_lon, zoom):
    x0,x1 = lon_to_tile_x(min_lon,zoom), lon_to_tile_x(max_lon,zoom)
    y0,y1 = lat_to_tile_y(max_lat,zoom), lat_to_tile_y(min_lat,zoom)
    canvas = Image.new('RGB', ((x1-x0+1)*256,(y1-y0+1)*256))
    for ix,x in enumerate(range(x0,x1+1)):
        for iy,y in enumerate(range(y0,y1+1)):
            canvas.paste(fetch_tile(x,y,zoom),(ix*256,iy*256))
            time.sleep(0.05)
    nw_lat,nw_lon = tile_to_latlon(x0,   y0,   zoom)
    se_lat,se_lon = tile_to_latlon(x1+1, y1+1, zoom)
    W,H = canvas.size
    l = int((min_lon-nw_lon)/(se_lon-nw_lon)*W)
    r = int((max_lon-nw_lon)/(se_lon-nw_lon)*W)
    t = int((max_lat-nw_lat)/(se_lat-nw_lat)*H)
    b = int((min_lat-nw_lat)/(se_lat-nw_lat)*H)
    return canvas.crop((max(0,l),max(0,t),min(W,r),min(H,b)))


# ── Load model ────────────────────────────────────────────────────────────────
DEVICE     = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
checkpoint = torch.load(MODEL_PATH, map_location=DEVICE)

VIIRS_BAND_INDICES = checkpoint['viirs_band_indices']   # [0, 1, 2]
FRP_CHANNEL_IDX    = checkpoint['frp_channel_idx']      # 3
VIIRS_CHANNELS     = checkpoint['viirs_channels']       # 4
SPATIAL_SIZE       = 128
LULC_CLASSES       = 12

enc_weight = checkpoint['model']['spatial_encoder.enc1.conv.0.block.0.weight']
C_VIIRS    = enc_weight.shape[1] - 8
model      = DeepFireForecaster(viirs_channels=C_VIIRS).to(DEVICE)
model.load_state_dict(checkpoint['model'])
model.eval()
print(f'Model loaded ✅  epoch={checkpoint["epoch"]}  '
      f'val_loss={checkpoint["val_loss"]:.5f}  '
      f'val_iou={checkpoint["val_iou"]:.4f}')
print(f'Landscape bands : {VIIRS_BAND_INDICES}')
print(f'FRP channel     : position {FRP_CHANNEL_IDX}')

#Load VIIRS landscape bands
event_path = all_event_dirs[EVENT_IDX]
event_name = os.path.basename(event_path)
day_files  = sorted(glob.glob(os.path.join(event_path, 'VIIRS_Day',  '*.tif')))
lulc_files = glob.glob(os.path.join(event_path, 'ESRI_LULC', '*.tif'))
date_label = os.path.basename(day_files[DAY_IDX]).replace('.tif','')

arr, crs, bounds = read_selected_bands(day_files[DAY_IDX], VIIRS_BAND_INDICES)
viirs_norm       = normalise_arr(arr)                       # [3, H, W]
viirs_resized    = resize_arr(viirs_norm, SPATIAL_SIZE)     # [3, S, S]

# LULC
if lulc_files:
    with rasterio.open(lulc_files[0]) as src:
        lulc_raw = np.nan_to_num(src.read(1).astype(np.float32), nan=0.0)
else:
    lulc_raw = np.zeros((arr.shape[1], arr.shape[2]), dtype=np.float32)

lulc_t = torch.tensor(lulc_raw).unsqueeze(0).unsqueeze(0).float()
lulc_t = F.interpolate(lulc_t, size=(SPATIAL_SIZE,SPATIAL_SIZE), mode='nearest')
lulc_resized = lulc_t.squeeze().long().clamp(0, LULC_CLASSES-1)

#  Satellite image
cached_path = os.path.join(SATELLITE_DIR, event_name,
                           f'{event_name}_satellite.png')
if os.path.exists(cached_path):
    print('Loading cached satellite image ...')
    sat_img = Image.open(cached_path).convert('RGB')
else:
    print('Fetching from ESRI ...')
    min_lat,min_lon,max_lat,max_lon = get_bbox_latlon(bounds, crs)
    zoom    = ZOOM if ZOOM else auto_zoom(min_lat,min_lon,max_lat,max_lon)
    sat_img = fetch_esri_image(min_lat,min_lon,max_lat,max_lon,zoom)

sat_img = sat_img.resize((SPATIAL_SIZE, SPATIAL_SIZE), Image.LANCZOS)
sat_np  = np.array(sat_img)

print(f'\nEvent : {event_name}  —  {date_label}')

# CELL 4 — Pick ignition area


fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle(
    f'{event_name}  —  {date_label}\n'
    f'Image is {SPATIAL_SIZE}×{SPATIAL_SIZE} px  '
    f'(x = left→right,  y = top→bottom)',
    fontsize=11, fontweight='bold'
)
axes[0].imshow(sat_np)
axes[0].set_title('Satellite image', fontsize=10); axes[0].axis('off')

axes[1].imshow(sat_np)
step = SPATIAL_SIZE // 8
for i in range(0, SPATIAL_SIZE, step):
    axes[1].axhline(i, color='white', linewidth=0.4, alpha=0.6)
    axes[1].axvline(i, color='white', linewidth=0.4, alpha=0.6)
    if i > 0:
        axes[1].text(i, 2,  str(i), color='white', fontsize=6, ha='center')
        axes[1].text(2, i,  str(i), color='white', fontsize=6, va='center')
axes[1].set_title('Grid overlay — use to estimate coordinates', fontsize=10)
axes[1].set_xlim(0, SPATIAL_SIZE); axes[1].set_ylim(SPATIAL_SIZE, 0)
axes[1].axis('off')
plt.tight_layout(); plt.show()

# ── Set ignition box here ─────────────────────────────────────────────────────
IGN_X1 = 16   # ← left edge
IGN_Y1 = 80   # ← top edge
IGN_X2 = 32  # ← right edge
IGN_Y2 = 96   # ← bottom edge

# Fire intensity settings
FIRE_PEAK  = 1.0   # peak FRP value (1.0 = maximum fire intensity)
FIRE_SIGMA = 5.0   # Gaussian spread in pixels around the box edge

S = SPATIAL_SIZE - 1
drawn_rect = {
    'x1': max(0, min(IGN_X1, S)), 'y1': max(0, min(IGN_Y1, S)),
    'x2': max(0, min(IGN_X2, S)), 'y2': max(0, min(IGN_Y2, S)),
}

#  Build FRP input map

frp_input = np.zeros((SPATIAL_SIZE, SPATIAL_SIZE), dtype=np.float32)
x1,y1 = drawn_rect['x1'], drawn_rect['y1']
x2,y2 = drawn_rect['x2'], drawn_rect['y2']
frp_input[y1:y2+1, x1:x2+1] = FIRE_PEAK
frp_input = gaussian_filter(frp_input, sigma=FIRE_SIGMA)
if frp_input.max() > 0:
    frp_input = frp_input / frp_input.max() * FIRE_PEAK

# Preview
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('Ignition area preview', fontsize=11, fontweight='bold')

axes[0].imshow(sat_np)
rect = patches.Rectangle(
    (x1, y1), x2-x1, y2-y1,
    linewidth=2, edgecolor='red', facecolor='red', alpha=0.35)
axes[0].add_patch(rect)
axes[0].set_title(
    f'Satellite + ignition box\nx=[{x1},{x2}]  y=[{y1},{y2}]', fontsize=10)
axes[0].axis('off')

axes[1].imshow(sat_np)
axes[1].imshow(frp_input, cmap='hot', vmin=0, vmax=1, alpha=0.7)
axes[1].set_title('FRP input channel', fontsize=10)
axes[1].axis('off')

plt.tight_layout(); plt.show()

#  Run prediction and display results
fire_cmap = LinearSegmentedColormap.from_list(
    'fire', [(0,0,0,0),(1,0.5,0,0.5),(1,0,0,0.85)], N=256)


input_arr = np.concatenate(
    [viirs_resized, frp_input[np.newaxis]], axis=0)   # [4, S, S]

viirs_t = torch.tensor(input_arr, dtype=torch.float32) \
               .unsqueeze(0).unsqueeze(0).to(DEVICE)  # [1, 1, 4, S, S]
lulc_in = lulc_resized.unsqueeze(0).to(DEVICE)        # [1, S, S]

with torch.no_grad():
    pred_t, _ = model(viirs_t, lulc_in)

pred_np = pred_t.cpu().squeeze().numpy()              # [S, S]

#  Plot
fig, axes = plt.subplots(1, 4, figsize=(22, 5))
fig.suptitle(
    f'Fire Spread Prediction — {event_name}  ({date_label})\n'
    f'FRP input → model → next day prediction  |  threshold={PRED_THRESHOLD}',
    fontsize=11, fontweight='bold'
)

# Panel 1 — satellite + ignition box
axes[0].imshow(sat_np)
axes[0].add_patch(patches.Rectangle(
    (x1,y1), x2-x1, y2-y1,
    linewidth=2, edgecolor='red', facecolor='red', alpha=0.35))
axes[0].set_title('Ignition area', fontsize=10); axes[0].axis('off')

# Panel 2 — FRP input channel (what model received)
axes[1].imshow(sat_np)
axes[1].imshow(frp_input, cmap='hot', vmin=0, vmax=1, alpha=0.7)
axes[1].set_title('FRP input\n(current fire state)', fontsize=10)
axes[1].axis('off')

# Panel 3 — predicted spread overlaid on satellite
axes[2].imshow(sat_np)
axes[2].imshow(pred_np, cmap=fire_cmap, vmin=0, vmax=1)
axes[2].set_title(f'Predicted spread\n(next day)', fontsize=10)
axes[2].axis('off')

# Panel 4 — raw probability heatmap
im = axes[3].imshow(pred_np, cmap='hot', vmin=0, vmax=1)
axes[3].set_title(f'Probability map\n(max={pred_np.max():.3f})', fontsize=10)
axes[3].axis('off')
fig.colorbar(im, ax=axes[3], fraction=0.046, pad=0.04, label='Probability')

plt.tight_layout()
save_path = os.path.join(SAVE_DIR,
    f'demo_frpinput_{event_name}_{date_label}.png')
os.makedirs(SAVE_DIR, exist_ok=True)
plt.savefig(save_path, dpi=200, bbox_inches='tight')
plt.show(); plt.close()
print(f'Saved → {save_path}')

fire_px = int((pred_np >= PRED_THRESHOLD).sum())
print(f'\nPrediction summary:')
print(f'  Fire pixels predicted  : {fire_px} / {SPATIAL_SIZE**2} '
      f'({100*fire_px/SPATIAL_SIZE**2:.1f}%)')
print(f'  Max predicted prob     : {pred_np.max():.4f}')
print(f'  Input fire pixels      : '
      f'{int((frp_input >= PRED_THRESHOLD).sum())} '
      f'({100*(frp_input>=PRED_THRESHOLD).mean():.1f}%)')